### ISSUE TITLE
Change `U.view` to better support objects with multiple observables

### ISSUE THREAD

**Issue by rikutiira** [calmm-js/karet.util#11]
Current implementation of `U.view`:

```
export const view = I_curry((l, xs) => {
  if (xs instanceof AbstractMutable) {
    return template(l) instanceof Observable
      ? new Join(combines(l, l => xs.view(l)))
      : xs.view(l)
  } else {
    return combines(l, xs, L.get)
  }
})
```

I have an use-case like this:

```
var template = {
	foo: U.variable(),
	bar: U.atom('bar')
}

var bar = U.view('bar', template)

bar.log()
```

`bar.log()` never logs anything because `foo` doesn't have a value.

Perhaps change the view implementation to take this into consideration? Same issue happens with lifted Ramda `R.prop` (and probably same applies to other Ramda lens functions).

In case of `U.view`, perhaps something like this would suffice?

```
export const view = I_curry((l, xs) => {
  if (xs instanceof AbstractMutable) {
    return template(l) instanceof Observable
      ? new Join(combines(l, l => xs.view(l)))
      : xs.view(l)
  } else if (xs instanceof Observable) {
    return combines(l, xs, L.get)
  } else {
    return combines(l, (l) => L.get(l, xs))
  }
})
```

**Comment by polytypic** [comment]
Hmm...  I see the desire, but my first reaction is that this does not fundamentally solve the problem.

With the suggested implementation, `view('bar', {bar: U.atom({baz: 101})})` would just return the atom `U.atom({baz: 101})`, which kind of seems plausible.  However, `view(['bar', 'baz'], {bar: U.atom({baz: 101})})` would return `undefined`, which is probably not what one might expect.  It would attempt to simply take the `baz` property from the atom object itself.

I presume the use-case is simplified from real code, but I wonder whether in that case you could just write (the equivalent of) `template.bar`?

BTW, in fact, I've actually been considering (although probably will not be) simplifying `U.view` to

```js
export const view = I.curry((l, xs) =>
  template(l) instanceof Observable
    ? new Join(combines(l, l => xs.view(l)))
    : xs.view(l)
)
```

because lifted `L.get` handles the case where `xs` is observable or plain value (rather than an atom).

**Comment by rikutiira** [comment]
Yeah, you are right, didn't consider that. I agree that it's better to work the way you said, that'd cause a lot of confusion.

Yeah, my use-case is a bit more complex (I have large state template with multiple atoms) and I am indeed doing `template.bar` at the moment, but I generally try to avoid doing that so we don't have to think about whether something is object literal or observable.

I'll close this as I don't think there's really any way to make this work without compromise.
